[package]
name = "runnner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
gl = "0.14.0"
glm = "0.2.3"
image = "0.24.6"
